config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: { minimum: 3 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: true, length: { minimum: 3 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) unless session[:user_id].nil?
  end

  def logged_in?
    return true if current_user

    false
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params.require(:comment).permit(:comment))
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    @comment.save
    redirect_to post_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(params.require(:post).permit(:title, :content))
    post.user_id = current_user.id
    post.save
    redirect_to post_path(post.id)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email])
    session[:user_id] = @user.id if @user&.authenticate(params[:session][:password])
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(params.require(:user).permit(:username, :password, :email))
    @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def comments_size(comments)
    return comments if comments.size.positive?

    []
  end

  def comm(comm)
    if comm
      comm.comment
    else
      false
    end
  end

  def aut(comm)
    if comm
      comm.user.username
    else
      false
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Micro-Reddit', root_path , class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

            <% if logged_in? %>
                <li class="nav-item active">  <%= link_to current_user.username, '#', class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to "Log out", logout_path,  method: :delete,  class: "nav-link"%></li>
                
                <li class="nav-item"><%= link_to "view posts", posts_path, class: "nav-link"%></li>
                <li class="nav-item"><%= link_to "create post", new_post_path, class: "nav-link"%></li>
            <% else %>
                   <li><%= link_to "Login", login_path  %></li>
                   <li><%= link_to "Sign Up", signup_path  %></li>
            <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MicroReddit" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/header'%>

    <div class="container mt-4">
      <div class="row">
        <div class="col-lg-9 mx-auto">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2020</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'title'%>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', placeholder: 'content'%>
  </div>
  <button type="submit" class="btn btn-primary">Create Post</button>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="card">
    <div class="card-body">
        <p class="card-text"><%=link_to post.title, post_path(post.id)%></p>
    </div>
    <div class="card-footer">
        <small>Created on: <%= Date.today - post.created_at.day%></small>
    </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<%= render 'posts/form'%>

app/views/posts/show.html.erb
<div class="card text-center">
  <div class="card-body">
    <h5 class="card-title h2"><%= @post.title%></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @post.user.username%></h6>
    <p class="card-text"><%= @post.content%></p>
    <div class="card">
    <ul class="list-group list-group-flush">

          <p class="text-muted">Here are the comments: </p>

          <% comments_size(@post.comments).each do |comm|%>
          <li class="list-group-item d-flex flex-column"><%= comm(comm) %>
          <small class="text-muted"> <%= aut(comm) %> </small>
          </li>
        <% end %>
    </ul>
  </div>
  </div>
 <%= form_with(model: [ @post, Comment.new ], local: true) do |f| %>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: 'form-control', placeholder: 'title'%>
  </div>
  <button type="submit" class="btn btn-primary">Comment</button>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |f| %>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control', placeholder: 'example@email.com'%>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', placeholder: 'example@email.com'%>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', placeholder: 'example@email.com'%>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Welcome to Micro-reddit</h1>
  <p class="lead">Here you can post about whatever you desire and your friends can comment.</p>
  <hr class="my-2">
  <p>Just be nice to other people.</p>
  <p class="lead">
    <%= link_to 'Create your first post', new_post_path, class: "btn btn-primary btn-lg"%>
  </p>
</div>